name: Sync-Check

on:
  workflow_call:

jobs:
  vanilla:
    name: Vanilla
    uses: ./.github/workflows/Test.SyncCheck.yml
    with:
      id: vanilla_full
      name: Vanilla
      build-cfg: Debug
      tas-repository: VampireFlower/CelesteTAS
      tas-revision: eb4550a253be97fd4942a5e609fe2a60e980f7ca
      tas-files: |
        0 - Any%.tas
        0 - All A Sides.tas
        0 - All B Sides.tas
        0 - All C Sides.tas
        0 - 100%.tas
        0 - 202 Berries.tas

  strawberryjam:
    name: Strawberry Jam
    uses: ./.github/workflows/Test.SyncCheck.yml
    with:
      id: strawberryjam_full
      name: Strawberry Jam
      build-cfg: Debug
      tas-repository: VampireFlower/StrawberryJamTAS
      tas-revision: df83fdee5f70bbebd8bd2a04a4e9608522486e20
      tas-files: |
        0-SJ All Levels.tas
      required-mods: StrawberryJam2021
